### ISSUE TITLE
Toggle feature?

### ISSUE THREAD

**Issue by jebaum** [xiyaowong/nvim-cursorword#12]
I know part of the goal of this is being as simple as possible - would you be willing to accept a PR for a feature to toggle highlighting on and off (probably implemented by clearing + reinstating the relevant autocmds)? I currently use `vim-brightest` which has a `BrightestToggle` command that is very handy, since I prefer to have highlighting off most of the time but be able to selectively turn it on.

I'm happy to send a PR to add this if you're ok with the idea

**Comment by xiyaowong** [comment]
Welcome!

**Comment by xiyaowong** [comment]
closed by #13
