### ISSUE TITLE
How to change background color?

### ISSUE THREAD

**Issue by peter-subsplash** [xiyaowong/nvim-cursorword#14]
Thanks for your plugin. 

I've been trying to get rid of the default underline and instead give it a subtle background color (preferably one from Gruvbox), but my attempts at commanding style changes have failed, eg `:hi default CursorWord guibg=Black guifg=Red` changes nothing.

Is setting bg/fg not allowed?

**Comment by liaohui5** [comment]
> Thanks for your plugin.
> 
> I've been trying to get rid of the default underline and instead give it a subtle background color (preferably one from Gruvbox), but my attempts at commanding style changes have failed, eg `:hi default CursorWord guibg=Black guifg=Red` changes nothing.
> 
> Is setting bg/fg not allowed?

hi, you can use this plugin to custom highlight, the functionality is the same as that of this plug-in

https://github.com/yamatsum/nvim-cursorline
