### ISSUE TITLE
stopped working

### ISSUE THREAD

**Issue by ChrisTsou** [xiyaowong/nvim-cursorword#2]
after 666f5c0b69d634f11508aae6d1dcacccff2730c3 it stopped working for me

**Comment by xiyaowong** [comment]
don't know, it works fine for me

**Comment by xiyaowong** [comment]
run `:hi CursorWord`, what's the output?

**Comment by ChrisTsou** [comment]
ok i was wrong, it works but i need to leave the cursor on the word for around 4 seconds

hi Cursorword is fine, its underline

**Comment by xiyaowong** [comment]
that's because using CursorHold now, I think is better than CursorMoved.  you can try to reduce the updatetime

**Comment by ChrisTsou** [comment]
I set updatetime to 10ms, i like the live underline, it works fine. i have swapfile set to false though, not sure about implications if its on, on big files,
