### ISSUE TITLE
updatetime

### ISSUE THREAD

**Issue by ChrisTsou** [xiyaowong/nvim-cursorword#3]
So today i wanted to make the neovim lsp hover appear after a while on CursorHold autocmd, but then it shares update time with this. i want something like 10ms for this to be realtime and 500ms for hover to appear after a while. separate option or global is better i think.

**Comment by xiyaowong** [comment]
ok  i will revert to use CursorMoved

**Comment by ChrisTsou** [comment]
i also saw something about updatetime on ulttest repo and i dont think its meant to be really low

**Comment by ChrisTsou** [comment]
You could also make it an option for the user to choose.

**Comment by xiyaowong** [comment]
this plugin is very minimal. it's unnecessary to add a option😜
