### ISSUE TITLE
[BUG] E5108: Error executing lua Vim:E54: Unmatched \(

### ISSUE THREAD

**Issue by RunningIkkyu** [xiyaowong/nvim-cursorword#4]
# Description 

Got Error when moved cursor to specific characters.

The test text is as blew:

```text
:let g:ft_ignore_pat = '\.\(Z\|gz\|bz2\|zip\|tgz\)$'
  This means that the contents of compressed files are not inspected.
```

When the cursor was on `contents`, the plugin works normally.  Then press <kbd>k</kbd> to move cursor to the first line, the error happend: 

```txt
E5108: Error executing lua Vim:E54: Unmatched \(
```

# Expected behavior

Move normally and plugin underline the word correctly even got special characters like `\(`.

# Actual behavior

Got error message, and the plugin cannot work normally.

# Step to reproduce

My Environment:

Nvim: NVIM v0.5.0-dev+1386-
nvim-cursorword: latest(66f52ac73a93cc3778be441ad6e6b8264c82daf2)
System: Mac OS(m1)

Copy below code to nvim (0.5.0+)

```text
:let g:ft_ignore_pat = '\.\(Z\|gz\|bz2\|zip\|tgz\)$'
  This means that the contents of compressed files are not inspected.
```

Move cursor to any `\` will cause the error.

**Comment by xiyaowong** [comment]
Following your steps, the error was not reproduced
![GIF](https://user-images.githubusercontent.com/47070852/128616059-bb2b9513-9c9e-44f4-8f08-b4c59cf6aaaa.gif)

**Comment by RunningIkkyu** [comment]
Sry it works fine in normal files.

Try `:help filetype`, then jump to line 145, and the error happened.

**Comment by xiyaowong** [comment]
should be fixed now
