### ISSUE TITLE
Which the plugin of indent guider in the demo GIF?

### ISSUE THREAD

**Issue by ArtisticZhao** [xiyaowong/nvim-cursorword#5]
![2021-08-30_14-07](https://user-images.githubusercontent.com/22850287/131293068-bc56c384-29f8-4417-ad90-98300c8859ed.png)

It seems can show the indent guider in a blank line.

Thank you!

**Comment by xiyaowong** [comment]
https://github.com/lukas-reineke/indent-blankline.nvim
