### ISSUE TITLE
:hi link is not recognized

### ISSUE THREAD

**Issue by jceb** [xiyaowong/nvim-cursorword#6]
I tried to set up a custom highlighting by linking it to another highlighting group. However, that doesn't seem to work as it's overwritten by the `M.highlight` function.

I have the following in my packer configuration:

```lua
    use({ "xiyaowong/nvim-cursorword", setup=function()
         vim.cmd([[
         hi link CursorWord DiffAdd
         ]])
    end})
```

**Comment by jceb** [comment]
It seems that for a brief moment during initialization `CursorWord` is set to `cleared`. I guess that happens when the colorscheme is initialized .. and then it's overwritten by `M.highlight`.

**Comment by jceb** [comment]
I found this workaround that does the job, however I don't think it's 100% stable as it's racing against the `CursorWord` augroup:

```lua
    use({ "xiyaowong/nvim-cursorword", setup=function()
         vim.cmd([[
         hi link CursorWord DiffAdd
         augroup MyCursorWord
             autocmd!
             autocmd VimEnter,Colorscheme * hi link CursorWord DiffAdd
         augroup END
         ]])
    end})
```

**Comment by xiyaowong** [comment]
> however I don't think it's 100% stable as it's racing against the `CursorWord` 

it's stable. custom highlights settings should run after ColorScheme
